Fix syntax error in od_auth.py
derrix060/onedriveClient pull request #41
Opened 2018-12-16 19:54 UTC by baztian

2018-12-17 00:35 UTC, derrix060 requested changes

2018-12-17 00:35 UTC, derrix060 commented on onedrive_client/od_auth.py
> +                "Failed to read user profile:{data['error']['message']}")
This is not a syntax error, this is using the [f-string](https://www.python.org/dev/peps/pep-0498/).


I've just saw now that it requires python 3.6+. Please change to the normal `format` syntax:

```python
'Failed to read user profile: {}'.format(data['error']['message'])
```

2018-12-18 00:40 UTC, derrix060 approved these changes

2018-12-18 00:41 UTC, derrix060 commented
There are some errors on the checks that are not related with your changes. I'll try to fix them today and merge your PR.

Again, thanks for contributing for this project.

2019-03-18 10:33 UTC, Modelmat commented
Should this be force merged?

2019-03-18 18:14 UTC, merged